#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /
   controller: App\Controller\PagesController::index

posts.index:
   path: /posts
   controller: App\Controller\PostsController::index